version: 0.0
os: linux
files:
  - source: ./build.zip
    destination: /home/systemltd/nodejs
    
file_exists_behavior: OVERWRITE
hooks:
  AppicationStop:
   - location: stop.sh
     timeout: 300
     runas: systemsltd
  BeforeInstall:
   - location: install_dependencies.sh
     timeout: 300
     runas: systemsltd
  AfterInstall:
   - location: build.sh
     timeout: 300
     runas: systemsltd
  ApplicationStart:
   - location: start.sh
     timeout: 300
     runas: systemsltd
   
