version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
   - location: install_dependencies.sh
     timeout: 300
     runas: ubuntu
  Install:
   - location: build.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: start.sh
     timeout: 300
     runas: ubuntu
   
