version: 0.0
os: linux

    
file_exists_behavior: OVERWRITE
hooks:
  AppicationStop:
   - location: stop.sh
     timeout: 300
     runas: ubuntu
  BeforeInstall:
   - location: install_dependencies.sh
     timeout: 300
     runas: ubuntu
  AfterInstall:
   - location: build.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: start.sh
     timeout: 300
     runas: ubuntu
   
